<?php
// Heading
$_['heading_title']           = 'Automatic SEO Title';

// Text
$_['text_title']              = 'Automatic SEO Title';
$_['text_success']            = 'Success! You have modified Automatic SEO Title!';
$_['button_save']             = 'Save';
$_['button_cancel']           = 'Cancel';
$_['text_module']             = 'Modules';
$_['text_yes']                = 'Yes';
$_['text_no']                 = 'No';
$_['text_edit']               = 'Edit extension Automatic SEO Title';
$_['text_allowed_patern']     = 'Allow pattern:';
$_['text_legend_title']       = 'Settings for Title';
$_['text_legend_description'] = 'Settings for Description';
$_['text_legend_keywords']    = 'Settings for Description';
$_['text_rewrite_help']       = 'Trust automatic generation (ignore manual filling). If the field is not filled, the automatic generation of';

//Tabs
$_['tab_settings']            = 'Settings';
$_['tab_help']                = 'Support|HELP';

// Entry
$_['entry_product']           = 'Pattern for products:';
$_['entry_category']          = 'Pattren for category:';
$_['entry_manufacturer']      = 'Pattern for manufacturer:';
$_['entry_page']              = 'Add text for pagination:';
$_['entry_status']            = 'Status';
$_['entry_rewrite']           = 'Rewrite meta_title';
$_['entry_descr_rewrite']     = 'Rewrite meta_description';
$_['entry_keyw_rewrite']      = 'Rewrite meta_keywords';

// Error
$_['ast_error_access']        = 'You do not have permission to modify Automatic SEO Title.';

// help
$_['text_support']            = '<h2>Automatic generation headings (title) of product pages, category, manufacturer.</h2><p>Title is automatically generated when the product page, category, manufacturer is generated by the selected pattern 
for different language schemes.</p><p>In the case of the formation of a title for pages with pagination (categories, manufacturer), the module allows you to add additional text.</p><p>This module is useful for stores with a large number of products, categories, when managing seo tags becomes difficult and labor-intensive.</p><p>With the help of it, the time is saved when data for pages, categories, manufacturer (brand) changes.</p>
';
